<a href="https://colab.research.google.com/github/innovinitylabs/learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [388]:
import torch

In [389]:
# mps_device = torch.device('mps')

In [390]:
# class Conf: dev = torch.device("mps")

# introduction to tensors

## creating tensors

pytorch tensors are created using `torch.tensors`

### Scalar

In [391]:
scalar = torch.tensor(7)
scalar

tensor(7)

to get dimensions

In [392]:
scalar.ndim

0

to get the number without type

In [393]:
scalar.item()

7

### Vector

In [394]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [395]:
vector.ndim

1

easy way to remember dimension is by number of square brackets

In [396]:
vector.shape

torch.Size([2])

shape gives how elements in tensor are arranged.

### MATRIX

In [397]:
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [398]:
MATRIX.ndim

2

In [399]:
MATRIX.shape

torch.Size([2, 2])

In [400]:
MATRIX[0]

tensor([7, 8])

### TENSOR

In [401]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [402]:
TENSOR.ndim

3

In [403]:
TENSOR.shape

torch.Size([1, 3, 3])

In [404]:
TENSOR[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

random tensors are important because many Neural networks starts with random numbers

In [405]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1994, 0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547]])

In [406]:
random_tensor.ndim

2

In [407]:
random_huge_tensor = torch.zeros(4,5)
random_huge_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [408]:
random_huge_tensor.dtype

torch.float32

In [409]:
torch.__version__

'2.1.0'

In [410]:
zttendep = torch.arange(0, 10)
zttendep

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [411]:
ten = torch.tensor([11, 22, 33])

In [412]:
ten * 10

tensor([110, 220, 330])

In [413]:
torch.mul(ten, 11)

tensor([121, 242, 363])

In [414]:
ten * ten

tensor([ 121,  484, 1089])

In [415]:
twotwo = torch.tensor([[1, 2],
                       [3, 4]])

In [416]:
twotwo * twotwo

tensor([[ 1,  4],
        [ 9, 16]])

In [417]:
torch.matmul(twotwo, twotwo)

tensor([[ 7, 10],
        [15, 22]])

In [418]:
torch.matmul(ten, ten)

tensor(1694)

In [419]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

In [420]:
tensor1.size()

torch.Size([10, 3, 4])

In [421]:
tensor2.size()

torch.Size([4])

In [422]:
tensor1, tensor2

(tensor([[[-0.7746,  0.0349,  0.3211,  1.5736],
          [-0.8455,  1.3123,  0.6872, -1.0892],
          [-0.4879, -1.4181,  0.8963,  0.0499]],
 
         [[ 2.2667,  1.1790, -0.4345, -1.3864],
          [-0.7360, -0.8371, -0.9224,  1.8113],
          [ 0.1606,  0.3672,  0.1754,  1.3852]],
 
         [[ 1.3835, -1.2024,  0.7078, -1.0759],
          [ 0.5357,  1.1754,  0.5612, -0.4527],
          [ 1.2780,  0.1453,  0.2311,  0.0087]],
 
         [[-0.1423,  0.1971, -1.1441,  0.3383],
          [-0.7508,  2.8140,  0.3598, -0.0898],
          [ 0.4584, -0.5644,  1.0563, -1.4692]],
 
         [[ 0.0516,  0.7281, -0.7106, -0.6021],
          [ 0.9604,  0.4048, -1.3543, -0.4976],
          [ 0.4835, -0.1976,  1.2683,  1.2243]],
 
         [[ 0.0981,  1.7423, -1.3527,  0.2191],
          [-0.4502, -0.6788,  0.5743,  0.1877],
          [-0.3576, -0.3165,  0.5886, -0.8905]],
 
         [[-0.3036, -0.9864,  0.1233,  0.3499],
          [ 0.6173, -0.1693,  0.2332,  4.0356],
          [ 0.5279,  1

In [423]:
torch.matmul(tensor1, tensor2)

tensor([[ 1.1235, -0.7773,  1.4945],
        [-3.0686,  1.8091,  0.1188],
        [-0.4425, -1.4373, -1.0214],
        [ 0.0337, -1.6449, -0.3990],
        [-0.8458, -1.2370,  0.3015],
        [-1.3807,  0.9372,  0.1946],
        [ 1.1117,  1.1822, -0.8264],
        [-0.3596, -0.0119,  0.3764],
        [-0.1126, -2.2423,  1.0101],
        [ 0.0663,  1.9814,  1.4668]])

In [424]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.8019, 0.8400, 0.4558],
        [0.9852, 0.9527, 0.5772],
        [0.5294, 0.5114, 0.3103]])

In [425]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [426]:
x.argmax()

tensor(9)

In [427]:
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [428]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [429]:
torch.reshape(x, (5,2))

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [430]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [431]:
torch.stack([x,x,x], dim= 1)

tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60],
        [70, 70, 70],
        [80, 80, 80],
        [90, 90, 90]])

In [432]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [433]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [434]:
x[:, 0] = 1
x , y

(tensor([[[[[1., 1.]],
 
           [[1., 1.]]]],
 
 
 
         [[[[1., 1.]],
 
           [[1., 1.]]]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [435]:
z = torch.unsqueeze(y, dim=1)
z

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [436]:
torch.unsqueeze(y, dim=0)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [437]:
torch.unsqueeze(y, dim=1)

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [438]:
torch.unsqueeze(y, dim=3)

tensor([[[[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]]]])

#### to check if squeeze shares memory

In [439]:
sqz = torch.arange(0,12, 2)
sqz

tensor([ 0,  2,  4,  6,  8, 10])

In [440]:
sqz = sqz.unsqueeze(dim=0)

In [441]:
sqz

tensor([[ 0,  2,  4,  6,  8, 10]])

In [442]:
sqz2 = sqz.squeeze( dim = 0)
sqz2

tensor([ 0,  2,  4,  6,  8, 10])

In [443]:
sqz2[1] = 69
sqz2

tensor([ 0, 69,  4,  6,  8, 10])

In [444]:
sqz

tensor([[ 0, 69,  4,  6,  8, 10]])

Reproducablity. random seed

In [445]:
r_seed = 42
torch.manual_seed(r_seed)
rand_a = torch.rand(3,2)
rand_a

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [446]:
torch.rand(3,2)

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])

In [447]:
torch.manual_seed(42)
torch.rand(3,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [448]:
torch.manual_seed(42)
rand_a == torch.rand(3,2)

tensor([[True, True],
        [True, True],
        [True, True]])

In [449]:
rand_a.device

device(type='cpu')

In [450]:
# mps_rans = rand_a.to(mps_device)

rand_a still stays on CPU. have to assign it to a variable to hold the migrated tensor on `mps` like above

In [451]:
# mps_rans.device

In [452]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


# Practice

using template given in course for ease

In [453]:
import torch
seed = 42

In [459]:
print(f'without setting any prior manual seed \n{torch.rand(3,3)}') #RANDOM

without setting any prior manual seed 
tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890]])


### torch.`random`.manual_seed()

In [465]:
torch.random.manual_seed(seed)
print(f'with random manual seed \n{torch.rand(3,3)}\n') # gave required values
print(f'without manual seed \n{torch.rand(3,3)}') #Different than above,but NOT SO RANDOM, FIXED VALUES

with random manual seed 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

without manual seed 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


### torch.manual_seed()

In [464]:
torch.manual_seed(seed)
print(f'with global manual seed \n{torch.rand(3,3)} \n') # gave required values
print(f'without manual seed \n{torch.rand(3,3)}') #Different than above,but NOT SO RANDOM, FIXED VALUES

with global manual seed 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) 

without manual seed 
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


In [462]:
print(f'without any random seen in new notebook block \n{torch.rand(3,3)}') #totally random

without any random seen in new notebook block 
tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])
