<a href="https://colab.research.google.com/github/innovinitylabs/learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# introduction to tensors

## creating tensors

pytorch tensors are created using `torch.tensors`

### Scalar

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

to get dimensions

In [ ]:
scalar.ndim

0

to get the number without type

In [ ]:
scalar.item()

7

### Vector

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

easy way to remember dimension is by number of square brackets

In [ ]:
vector.shape

torch.Size([2])

shape gives how elements in tensor are arranged.

### MATRIX

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

### TENSOR

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

random tensors are important because many Neural networks starts with random numbers

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9914, 0.2865, 0.3387, 0.7829],
        [0.5968, 0.4002, 0.1846, 0.3948],
        [0.2468, 0.3826, 0.8891, 0.6829]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_huge_tensor = torch.zeros(4,5)
random_huge_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
random_huge_tensor.dtype

torch.float32

In [ ]:
torch.__version__

'2.0.1+cu118'

In [ ]:
zttendep = torch.arange(0, 10)
zttendep

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten = torch.tensor([11, 22, 33])

In [ ]:
ten * 10

tensor([110, 220, 330])

In [ ]:
torch.mul(ten, 11)

tensor([121, 242, 363])

In [ ]:
ten * ten

tensor([ 121,  484, 1089])

In [ ]:
twotwo = torch.tensor([[1, 2],
                       [3, 4]])

In [ ]:
twotwo * twotwo

tensor([[ 1,  4],
        [ 9, 16]])

In [ ]:
torch.matmul(twotwo, twotwo)

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
torch.matmul(ten, ten)

tensor(1694)

In [ ]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

In [ ]:
tensor1.size()

torch.Size([10, 3, 4])

In [ ]:
tensor2.size()

torch.Size([4])

In [ ]:
tensor1, tensor2

(tensor([[[-2.2230e-01,  4.2975e-01,  1.4707e+00, -1.6043e+00],
          [ 5.0122e-01, -1.3725e-01, -1.8216e+00, -1.1192e-01],
          [-1.6278e+00, -1.6637e+00,  1.2189e+00, -1.3328e-01]],
 
         [[-5.8174e-01,  1.0118e+00,  2.1237e+00, -1.5237e+00],
          [-3.8247e-01,  7.9066e-01, -7.6108e-01,  3.1575e-01],
          [ 1.5340e-01, -1.3259e-01,  3.4987e-01,  6.8908e-01]],
 
         [[-1.8539e+00,  4.2483e-01,  8.7125e-01, -5.0088e-01],
          [ 1.5890e-01,  1.0034e+00,  1.0305e+00, -5.9715e-01],
          [-6.4127e-02,  3.8468e-01, -1.3273e+00, -1.8472e-01]],
 
         [[ 6.4431e-02, -1.5502e-01,  3.5146e-01,  7.2883e-01],
          [ 7.7614e-01,  3.9850e-01, -1.7361e+00,  1.3347e+00],
          [-2.1829e-01,  1.4346e+00,  7.5129e-02, -6.3495e-01]],
 
         [[-1.4162e+00, -7.2381e-01,  6.0590e-01,  2.0558e+00],
          [ 7.3234e-01, -4.4754e-02,  7.3256e-03, -6.4727e-01],
          [ 1.1965e+00,  6.7608e-01, -2.4693e-01,  2.0098e+00]],
 
         [[ 1.0717e-01, -

In [ ]:
torch.matmul(tensor1, tensor2)

tensor([[-0.7929, -1.7397,  3.1479],
        [-0.6860, -1.1728,  1.1754],
        [ 0.1496, -0.8373, -1.8360],
        [ 1.2613, -0.7688, -2.1662],
        [ 3.8286, -0.7738,  0.9322],
        [-0.9022,  2.6342, -1.6952],
        [ 1.6227,  0.8284, -2.1314],
        [-2.8306, -3.1135,  1.6085],
        [-2.3708,  0.2841,  0.0117],
        [-0.1099,  3.7269,  0.3986]])

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5626, 0.4257, 0.2064],
        [0.3928, 0.4644, 0.1513],
        [0.4054, 0.1894, 0.1437]])

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.reshape(x, (5,2))

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.stack([x,x,x], dim= 1)

tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60],
        [70, 70, 70],
        [80, 80, 80],
        [90, 90, 90]])

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
x[:, 0] = 1
x , y

(tensor([[[[[1., 1.]],
 
           [[1., 1.]]]],
 
 
 
         [[[[1., 1.]],
 
           [[1., 1.]]]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [ ]:
z = torch.unsqueeze(y, dim=1)
z

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [ ]:
torch.unsqueeze(y, dim=0)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
torch.unsqueeze(y, dim=1)

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [ ]:
torch.unsqueeze(y, dim=3)

tensor([[[[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]]]])

#### to check if squeeze shares memory

In [ ]:
sqz = torch.arange(0,12, 2)
sqz

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
sqz = sqz.unsqueeze(dim=0)

In [ ]:
sqz

tensor([[ 0,  2,  4,  6,  8, 10]])

In [ ]:
sqz2 = sqz.squeeze( dim = 0)
sqz2

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
sqz2[1] = 69
sqz2

tensor([ 0, 69,  4,  6,  8, 10])

In [ ]:
sqz

tensor([[ 0, 69,  4,  6,  8, 10]])

Reproducablity. random seed

In [ ]:
r_seed =
rand_a =

SyntaxError: ignored