<a href="https://colab.research.google.com/github/innovinitylabs/learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [506]:
import torch

In [507]:
# mps_device = torch.device('mps')

In [508]:
# class Conf: dev = torch.device("mps")

# introduction to tensors

## creating tensors

pytorch tensors are created using `torch.tensors`

### Scalar

In [509]:
scalar = torch.tensor(7)
scalar

tensor(7)

to get dimensions

In [510]:
scalar.ndim

0

to get the number without type

In [511]:
scalar.item()

7

### Vector

In [512]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [513]:
vector.ndim

1

easy way to remember dimension is by number of square brackets

In [514]:
vector.shape

torch.Size([2])

shape gives how elements in tensor are arranged.

### MATRIX

In [515]:
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [516]:
MATRIX.ndim

2

In [517]:
MATRIX.shape

torch.Size([2, 2])

In [518]:
MATRIX[0]

tensor([7, 8])

### TENSOR

In [519]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [520]:
TENSOR.ndim

3

In [521]:
TENSOR.shape

torch.Size([1, 3, 3])

In [522]:
TENSOR[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

random tensors are important because many Neural networks starts with random numbers

In [523]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5088, 0.9559, 0.7885, 0.2089],
        [0.4351, 0.1314, 0.2588, 0.5905],
        [0.7723, 0.9142, 0.0409, 0.8343]])

In [524]:
random_tensor.ndim

2

In [525]:
random_huge_tensor = torch.zeros(4,5)
random_huge_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [526]:
random_huge_tensor.dtype

torch.float32

In [527]:
torch.__version__

'2.1.0'

In [528]:
zttendep = torch.arange(0, 10)
zttendep

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [529]:
ten = torch.tensor([11, 22, 33])

In [530]:
ten * 10

tensor([110, 220, 330])

In [531]:
torch.mul(ten, 11)

tensor([121, 242, 363])

In [532]:
ten * ten

tensor([ 121,  484, 1089])

In [533]:
twotwo = torch.tensor([[1, 2],
                       [3, 4]])

In [534]:
twotwo * twotwo

tensor([[ 1,  4],
        [ 9, 16]])

In [535]:
torch.matmul(twotwo, twotwo)

tensor([[ 7, 10],
        [15, 22]])

In [536]:
torch.matmul(ten, ten)

tensor(1694)

In [537]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

In [538]:
tensor1.size()

torch.Size([10, 3, 4])

In [539]:
tensor2.size()

torch.Size([4])

In [540]:
tensor1, tensor2

(tensor([[[-4.3747e-01, -1.2201e+00, -5.8542e-01,  6.6637e-01],
          [-7.4266e-02, -2.0960e-01,  1.6632e-01,  1.4703e+00],
          [ 3.5699e-01,  9.1429e-01,  2.1882e+00, -9.8515e-01]],
 
         [[-2.4885e+00, -3.3132e-01,  8.4358e-01,  9.8745e-01],
          [ 1.2154e+00,  1.4200e+00, -5.4650e-02,  2.4700e-02],
          [-1.0641e+00, -7.6019e-01, -4.0751e-01,  9.6236e-01]],
 
         [[ 3.7145e-01,  2.6968e-01,  7.8999e-01,  9.4461e-01],
          [-1.5824e+00,  9.8713e-01,  1.1457e+00, -1.4181e-01],
          [-6.1301e-01,  1.3917e+00,  2.2285e-01,  6.8388e-01]],
 
         [[-1.3246e+00, -5.1608e-01,  6.0018e-01, -4.7022e-01],
          [ 1.3664e+00,  1.3947e+00, -7.3959e-01, -4.8333e-01],
          [-7.4029e-01,  3.1428e-01,  1.4156e-01,  1.0348e+00]],
 
         [[-1.4033e+00, -1.3271e+00, -9.9475e-01, -4.9400e-01],
          [ 1.1366e+00, -4.6184e-01,  1.4200e+00,  8.4852e-01],
          [-6.7529e-02,  9.4907e-01, -3.9834e-01,  6.8990e-01]],
 
         [[-1.3129e+00,  

In [541]:
torch.matmul(tensor1, tensor2)

tensor([[-1.8934, -0.6624, -0.6460],
        [-2.8364,  3.4018, -1.5092],
        [-0.2552, -0.1866,  2.1458],
        [-2.3372,  4.2475,  0.0798],
        [-2.0518, -2.0689,  2.2811],
        [ 0.8518,  1.0347, -1.7549],
        [ 0.5762, -1.1335,  3.1549],
        [-0.1947, -0.5688,  1.7666],
        [ 1.6269,  0.3540, -5.1272],
        [ 0.2196, -1.0530,  1.0319]])

In [542]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.5959, 0.3619, 0.0848],
        [0.6621, 0.5515, 0.5976],
        [0.6810, 0.5563, 0.5776]])

In [543]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [544]:
x.argmax()

tensor(9)

In [545]:
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [546]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [547]:
torch.reshape(x, (5,2))

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [548]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [549]:
torch.stack([x,x,x], dim= 1)

tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60],
        [70, 70, 70],
        [80, 80, 80],
        [90, 90, 90]])

In [550]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [551]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [552]:
x[:, 0] = 1
x , y

(tensor([[[[[1., 1.]],
 
           [[1., 1.]]]],
 
 
 
         [[[[1., 1.]],
 
           [[1., 1.]]]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [553]:
z = torch.unsqueeze(y, dim=1)
z

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [554]:
torch.unsqueeze(y, dim=0)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [555]:
torch.unsqueeze(y, dim=1)

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [556]:
torch.unsqueeze(y, dim=3)

tensor([[[[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]]]])

#### to check if squeeze shares memory

In [557]:
sqz = torch.arange(0,12, 2)
sqz

tensor([ 0,  2,  4,  6,  8, 10])

In [558]:
sqz = sqz.unsqueeze(dim=0)

In [559]:
sqz

tensor([[ 0,  2,  4,  6,  8, 10]])

In [560]:
sqz2 = sqz.squeeze( dim = 0)
sqz2

tensor([ 0,  2,  4,  6,  8, 10])

In [561]:
sqz2[1] = 69
sqz2

tensor([ 0, 69,  4,  6,  8, 10])

In [562]:
sqz

tensor([[ 0, 69,  4,  6,  8, 10]])

Reproducablity. random seed

In [563]:
r_seed = 42
torch.manual_seed(r_seed)
rand_a = torch.rand(3,2)
rand_a

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [564]:
torch.rand(3,2)

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])

In [565]:
torch.manual_seed(42)
torch.rand(3,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [566]:
torch.manual_seed(42)
rand_a == torch.rand(3,2)

tensor([[True, True],
        [True, True],
        [True, True]])

In [567]:
rand_a.device

device(type='cpu')

In [568]:
# mps_rans = rand_a.to(mps_device)

rand_a still stays on CPU. have to assign it to a variable to hold the migrated tensor on `mps` like above

In [569]:
# mps_rans.device

In [570]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


# Practice

using template given in course for ease

In [571]:
import torch
seed = 42

In [572]:
print(f'without setting any prior manual seed \n{torch.rand(3,3)}') #RANDOM

without setting any prior manual seed 
tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])


### torch.`random`.manual_seed()

In [573]:
torch.random.manual_seed(seed)
print(f'with random manual seed \n{torch.rand(3,3)}\n') # gave required values
print(f'without manual seed \n{torch.rand(3,3)}') #Different than above,but NOT SO RANDOM, FIXED VALUES
print(f'without manual seed \n{torch.rand(3,3)}')

with random manual seed 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

without manual seed 
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
without manual seed 
tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])


### torch.manual_seed()

In [574]:
torch.manual_seed(seed)
print(f'with global manual seed \n{torch.rand(3,3)} \n') # gave required values
print(f'without manual seed \n{torch.rand(3,3)}') #Different than above,but NOT SO RANDOM, FIXED VALUES
print(f'without manual seed \n{torch.rand(3,3)}')

with global manual seed 
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]]) 

without manual seed 
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
without manual seed 
tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])


In [575]:
print(f'without any random seen in new notebook block \n{torch.rand(3,3)}') #totally random

without any random seen in new notebook block 
tensor([[0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])
