<a href="https://colab.research.google.com/github/innovinitylabs/learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# mps_device = torch.device('mps')

In [ ]:
# class Conf: dev = torch.device("mps")

# introduction to tensors

## creating tensors

pytorch tensors are created using `torch.tensors`

### Scalar

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

to get dimensions

In [ ]:
scalar.ndim

0

to get the number without type

In [ ]:
scalar.item()

7

### Vector

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

easy way to remember dimension is by number of square brackets

In [ ]:
vector.shape

torch.Size([2])

shape gives how elements in tensor are arranged.

### MATRIX

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

### TENSOR

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

random tensors are important because many Neural networks starts with random numbers

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_huge_tensor = torch.zeros(4,5)
random_huge_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
random_huge_tensor.dtype

torch.float32

In [ ]:
torch.__version__

'2.1.0'

In [ ]:
zttendep = torch.arange(0, 10)
zttendep

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten = torch.tensor([11, 22, 33])

In [ ]:
ten * 10

tensor([110, 220, 330])

In [ ]:
torch.mul(ten, 11)

tensor([121, 242, 363])

In [ ]:
ten * ten

tensor([ 121,  484, 1089])

In [ ]:
twotwo = torch.tensor([[1, 2],
                       [3, 4]])

In [ ]:
twotwo * twotwo

tensor([[ 1,  4],
        [ 9, 16]])

In [ ]:
torch.matmul(twotwo, twotwo)

tensor([[ 7, 10],
        [15, 22]])

In [ ]:
torch.matmul(ten, ten)

tensor(1694)

In [ ]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

In [ ]:
tensor1.size()

torch.Size([10, 3, 4])

In [ ]:
tensor2.size()

torch.Size([4])

In [ ]:
tensor1, tensor2

(tensor([[[-4.9740e-01,  4.3959e-01, -7.5813e-01,  1.0783e+00],
          [ 8.0080e-01,  1.6806e+00,  3.5586e-01, -6.8662e-01],
          [ 6.1047e-01,  1.3347e+00, -2.3162e-01,  4.1759e-02]],
 
         [[-2.5158e-01,  8.5986e-01, -3.0973e-01, -3.9571e-01],
          [-2.2337e-01,  1.7174e+00,  3.1888e-01, -4.2452e-01],
          [ 3.0572e-01, -7.7459e-01,  3.4912e-02,  3.2110e-01]],
 
         [[-8.7979e-01, -6.0114e-01, -1.2742e+00,  2.1228e+00],
          [-1.2347e+00, -4.8791e-01, -1.4181e+00,  8.9627e-01],
          [ 7.8024e-02,  5.2581e-01, -4.8799e-01,  1.1914e+00]],
 
         [[-8.1401e-01, -7.3599e-01, -8.3713e-01, -9.2239e-01],
          [-6.3477e-02,  6.7561e-01, -9.7807e-02,  1.8446e+00],
          [-1.1845e+00,  1.3835e+00, -1.2024e+00,  7.0781e-01]],
 
         [[ 2.2181e+00,  5.2317e-01,  3.4665e-01, -1.9733e-01],
          [-1.0546e+00,  1.2780e+00,  1.4534e-01,  2.3105e-01],
          [ 5.6622e-02,  4.2630e-01,  5.7501e-01, -6.4172e-01]],
 
         [[-2.2064e+00, -

In [ ]:
torch.matmul(tensor1, tensor2)

tensor([[ 1.7704, -2.0725, -0.6184],
        [-0.6816, -1.3714,  0.6463],
        [ 3.9823,  2.4583,  1.5737],
        [-0.2915,  2.2701,  1.2931],
        [-1.3916,  0.0596, -1.3206],
        [ 0.3211,  1.1778, -1.6874],
        [-0.2686,  1.1440,  0.2308],
        [ 0.9053,  1.3927,  0.7286],
        [-0.1958, -1.4983, -0.5559],
        [ 2.2528,  1.2675,  1.4195]])

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.3733, 0.1723, 0.1614],
        [0.6364, 0.4897, 0.3335],
        [0.6082, 0.7847, 0.4129]])

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.reshape(x, (5,2))

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.stack([x,x,x], dim= 1)

tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60],
        [70, 70, 70],
        [80, 80, 80],
        [90, 90, 90]])

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [ ]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
x[:, 0] = 1
x , y

(tensor([[[[[1., 1.]],
 
           [[1., 1.]]]],
 
 
 
         [[[[1., 1.]],
 
           [[1., 1.]]]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [ ]:
z = torch.unsqueeze(y, dim=1)
z

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [ ]:
torch.unsqueeze(y, dim=0)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
torch.unsqueeze(y, dim=1)

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [ ]:
torch.unsqueeze(y, dim=3)

tensor([[[[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]]]])

#### to check if squeeze shares memory

In [ ]:
sqz = torch.arange(0,12, 2)
sqz

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
sqz = sqz.unsqueeze(dim=0)

In [ ]:
sqz

tensor([[ 0,  2,  4,  6,  8, 10]])

In [ ]:
sqz2 = sqz.squeeze( dim = 0)
sqz2

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
sqz2[1] = 69
sqz2

tensor([ 0, 69,  4,  6,  8, 10])

In [ ]:
sqz

tensor([[ 0, 69,  4,  6,  8, 10]])

Reproducablity. random seed

In [ ]:
r_seed = 42
torch.manual_seed(r_seed)
rand_a = torch.rand(3,2)
rand_a

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [ ]:
torch.rand(3,2)

tensor([[0.2566, 0.7936],
        [0.9408, 0.1332],
        [0.9346, 0.5936]])

In [ ]:
torch.manual_seed(42)
torch.rand(3,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [ ]:
torch.manual_seed(42)
rand_a == torch.rand(3,2)

tensor([[True, True],
        [True, True],
        [True, True]])

In [62]:
rand_a.device

device(type='cpu')

In [ ]:
# mps_rans = rand_a.to(mps_device)

rand_a still stays on CPU. have to assign it to a variable to hold the migrated tensor on `mps` like above

In [ ]:
# mps_rans.device

device(type='mps', index=0)

In [63]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


# Practice

using template given in course for ease