<a href="https://colab.research.google.com/github/innovinitylabs/learning-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# introduction to tensors

## creating tensors

pytorch tensors are created using `torch.tensors`

### Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

to get dimensions

In [3]:
scalar.ndim

0

to get the number without type

In [4]:
scalar.item()

7

### Vector

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

easy way to remember dimension is by number of square brackets

In [7]:
vector.shape

torch.Size([2])

shape gives how elements in tensor are arranged.

### MATRIX

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

### TENSOR

In [12]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]


tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random Tensors

random tensors are important because many Neural networks starts with random numbers

In [16]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8818, 0.0159, 0.8497, 0.9933],
        [0.0026, 0.0030, 0.0801, 0.8101],
        [0.8464, 0.0927, 0.5621, 0.9290]])

In [17]:
random_tensor.ndim

2

In [18]:
random_huge_tensor = torch.zeros(4,5)
random_huge_tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
random_huge_tensor.dtype

torch.float32

In [20]:
torch.__version__

'2.0.1+cu118'

In [21]:
zttendep = torch.arange(0, 10)
zttendep

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
ten = torch.tensor([11, 22, 33])

In [23]:
ten * 10

tensor([110, 220, 330])

In [24]:
torch.mul(ten, 11)

tensor([121, 242, 363])

In [25]:
ten * ten

tensor([ 121,  484, 1089])

In [26]:
twotwo = torch.tensor([[1, 2],
                       [3, 4]])

In [27]:
twotwo * twotwo

tensor([[ 1,  4],
        [ 9, 16]])

In [28]:
torch.matmul(twotwo, twotwo)

tensor([[ 7, 10],
        [15, 22]])

In [29]:
torch.matmul(ten, ten)

tensor(1694)

In [30]:
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

In [31]:
tensor1.size()

torch.Size([10, 3, 4])

In [32]:
tensor2.size()

torch.Size([4])

In [33]:
tensor1, tensor2

(tensor([[[-1.0682e+00,  4.5257e-02, -9.4842e-01,  2.0263e+00],
          [-5.4946e-01, -2.6315e+00,  1.1753e+00,  3.4621e-01],
          [ 1.4322e+00,  6.8608e-01, -2.2052e+00,  7.2196e-01]],
 
         [[ 1.0823e+00,  4.0381e-04,  9.2208e-01, -1.9716e+00],
          [-1.2373e-01,  1.1324e+00, -1.1527e+00,  1.3004e-01],
          [-5.1453e-01,  2.7098e-02,  1.3027e+00,  1.8764e+00]],
 
         [[ 6.1981e-01, -1.0977e-01, -3.2682e-01, -1.0733e+00],
          [-1.2991e+00, -1.1685e-01,  5.8894e-01, -1.3045e+00],
          [-4.6887e-01,  1.6827e+00,  5.8973e-01,  5.7057e-01]],
 
         [[ 7.8302e-01, -3.6423e-02,  1.1706e-01,  1.9744e-01],
          [-7.8933e-01,  1.9211e+00,  6.5791e-01, -4.8993e-01],
          [ 5.4919e-01, -1.3433e+00,  2.0589e-01, -3.6667e-01]],
 
         [[ 1.7115e+00,  1.3056e+00,  5.7995e-01, -1.8379e+00],
          [-3.5881e-01,  1.0873e+00, -1.1925e+00,  1.5379e-01],
          [ 1.3010e-01, -1.3869e+00, -2.5758e+00, -3.4704e-01]],
 
         [[ 3.9242e-01,  

In [34]:
torch.matmul(tensor1, tensor2)

tensor([[-0.7262, -2.9162,  3.8518],
        [ 0.7912,  1.1854, -1.4208],
        [ 0.9496, -2.3567, -0.0989],
        [ 1.0185, -0.5379, -0.1059],
        [ 2.6042,  0.8583,  1.0782],
        [ 0.3722,  1.7623, -2.3325],
        [-2.6411,  1.1752, -2.0532],
        [-0.2254,  2.0746,  1.1252],
        [ 3.4573,  1.4399,  2.5554],
        [-3.8206,  1.6887,  0.2384]])

In [35]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[1.1893, 1.0327, 0.3979],
        [0.5094, 0.5204, 0.2389],
        [1.2363, 1.0170, 0.3640]])

In [36]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
x.argmax()

tensor(9)

In [38]:
x.reshape(5,2)

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [39]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
torch.reshape(x, (5,2))

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [41]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
torch.stack([x,x,x], dim= 1)

tensor([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30],
        [40, 40, 40],
        [50, 50, 50],
        [60, 60, 60],
        [70, 70, 70],
        [80, 80, 80],
        [90, 90, 90]])

In [43]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [44]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [45]:
x[:, 0] = 1
x , y

(tensor([[[[[1., 1.]],
 
           [[1., 1.]]]],
 
 
 
         [[[[1., 1.]],
 
           [[1., 1.]]]]]),
 tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]))

In [46]:
z = torch.unsqueeze(y, dim=1)
z

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [47]:
torch.unsqueeze(y, dim=0)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [48]:
torch.unsqueeze(y, dim=1)

tensor([[[[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]]]])

In [49]:
torch.unsqueeze(y, dim=3)

tensor([[[[1.],
          [1.]],

         [[1.],
          [1.]]],


        [[[1.],
          [1.]],

         [[1.],
          [1.]]]])

#### to check if squeeze shares memory

In [50]:
sqz = torch.arange(0,12, 2)
sqz

tensor([ 0,  2,  4,  6,  8, 10])

In [51]:
sqz = sqz.unsqueeze(dim=0)

In [52]:
sqz

tensor([[ 0,  2,  4,  6,  8, 10]])

In [53]:
sqz2 = sqz.squeeze( dim = 0)
sqz2

tensor([ 0,  2,  4,  6,  8, 10])

In [54]:
sqz2[1] = 69
sqz2

tensor([ 0, 69,  4,  6,  8, 10])

In [55]:
sqz

tensor([[ 0, 69,  4,  6,  8, 10]])

Reproducablity. random seed

In [57]:
r_seed = 42
torch.manual_seed(r_seed)
rand_a = torch.rand(3,2)
rand_a

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [59]:
torch.rand(3,2)

tensor([[0.8694, 0.5677],
        [0.7411, 0.4294],
        [0.8854, 0.5739]])

In [60]:
torch.manual_seed(42)
torch.rand(3,2)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])

In [61]:
torch.manual_seed(42)
rand_a == torch.rand(3,2)

tensor([[True, True],
        [True, True],
        [True, True]])